# Appendix D: HTE Regression with Interaction Between Treatments and Cohorts

```{r Appendix  load_data,echo=FALSE}
# list of people
options(dplyr.summarise.inform = FALSE)


dt_roster <- read_csv('../../data/alumni_scrape.csv', col_types=cols()) %>%
  select(Email = email, Gender = gender, Year_Graduation = year_graduation, 
         Block = blocking_genderyear_assignments) %>% 
  mutate(Block = ifelse(
    Block == 1, "Direct", ifelse(
      Block == 2, "Philanthropic", "Control")))

# attrition, bounced, round 1 post-send merged status
r1_g1_bounce <- read_csv('../../data/round1_0702_group1_0702_0941.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')
r1_g2_bounce <- read_csv('../../data/round1_0702_group2_0702_1028.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')
r1_g3_bounce <- read_csv('../../data/round1_0702_group3_0702_1055.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) %>%
  filter(MStatus == 'BOUNCED')

# final status, sent, opened
r1_g1_status <- read_csv('../../data/round1_0702_group1_0708_1033.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r1_g2_status <- read_csv('../../data/round1_0702_group2_0708_1220.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r1_g3_status <- read_csv('../../data/round1_0702_group3_0708_1122.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r2_status <- read_csv('../../data/round2_0709_all_0716_1117.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r3_status <- read_csv('../../data/round3_0716_all_0722_1046.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r4_status <- read_csv('../../data/round4_0722_all_0723_1131.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 
r5_status <- read_csv('../../data/round5_0723_all_0724_1219.csv', col_types=cols()) %>%
  select(Email, MStatus = `Merge status`) 

# outcome, Qualtrics completion
dt_qualtrics <- read_csv('../../data/Qualtrics_downloaded_20210726.csv', col_types=cols()) %>%
  select(Email = RecipientEmail, Duration = `Duration (in seconds)`,
         Long = LocationLongitude, Lat = LocationLatitude) %>%
  slice(3:n()) %>%
  mutate(Duration = as.numeric(Duration),
         Long = as.numeric(Long),
         Lat = as.numeric(Lat))

# emails to exclude
ex_emails <- c('deveshkhandelwal@berkeley.edu', 'rahosbach@berkeley.edu',
               'tgao2020@berkeley.edu', 'tgao2020@berkely.edu',
               'mirza2020@berkeley.edu')


```

```{r Appeddix combine_data, echo= FALSE}
options(dplyr.summarise.inform = FALSE)

dt_agg <- 
  # roster does not contain us
  dt_roster %>%
  select(Email) %>%
  
  # bounce
  left_join(bind_rows(r1_g1_bounce, r1_g2_bounce, r1_g3_bounce) %>%
              add_column(bounce = 1) %>%
              select(-MStatus),
            by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # non-compliance: email_sent status for all 5 rounds
  left_join(
    # EMAIL_SENT not balanced.
    #bind_rows(r1_g1_status %>% filter(MStatus == 'EMAIL_SENT'),
    #          r1_g2_status %>% filter(MStatus == 'EMAIL_SENT'),
    #          r1_g3_status %>% filter(MStatus == 'EMAIL_SENT')) %>%
    #  filter(!Email %in% ex_emails) %>%
    #inner_join(r2_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
    #           by='Email') %>%
    
    # EMAIL_SENT is balanced in r3, r4 and r5
    dt_roster %>% select(Email) %>% add_column(MStatus='EMAIL_SENT') %>%
      
      inner_join(r3_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>%
      inner_join(r4_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>% # 4 & 5 are the same?
      inner_join(r5_status %>% filter(MStatus == 'EMAIL_SENT') %>% select(Email), 
                 by='Email') %>%
      add_column(non_complier = 1) %>%
      select(-MStatus),
    by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # compliers: people who opened at least 1 round
  mutate(complier = 1 - (bounce + non_complier)) %>%
  
  # completion: qualtrics records
  left_join(dt_qualtrics %>% select(Email) %>% add_column(completion=1), by = 'Email') %>%
  replace(is.na(.), 0) %>%
  
  # override some incorrect YAMM data
  # (these two lines correct rows for 4 people, all in the philanthropic group)
  # vishal, ansjory, taeil.goh, and davidhou
  mutate(non_complier = if_else(completion == 1, 0, non_complier),
         complier = if_else(completion == 1, 1, complier)) %>% 
  
  # meta data
  left_join(dt_roster, by = 'Email') %>%
  left_join(dt_qualtrics, by = 'Email') 

```



```{r Appendix cov_balance, echo=FALSE}
# dt_agg %>% 
#   select(Block, bounce, non_complier, complier, completion) %>%
#   gather(measure, value, -Block) %>%
#   group_by(Block, measure) %>%
#   summarise(value = sum(value)) %>%
#   spread(measure, value) %>%
#   select(Block, bounce, non_complier, complier, completion) %>%
#   mutate(all = bounce + non_complier + complier, .before=2)

# dt_agg %>% 
#   select(Block, bounce, non_complier, complier, completion) %>%
#   gather(measure, value, -Block) %>%
#   group_by(Block, measure) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() %>%
#   filter(measure != 'completion') %>%
#   mutate(measure = recode_factor(measure, 
#                                  bounce = "Email Bounced (Attrition)", 
#                                  non_complier = 'Did Not Open (Non-Complier)',
#                                  complier = "Opened Email (Complier)")) 


```


```{r Appendix hte_2, echo=FALSE,comment='' }
d <- data.table(dt_agg)
# HTE between grad year and treatment
m5 <- d[bounce == 0 & Gender != 'U', lm(completion ~ factor(Year_Graduation) * Block)]
rse5 <- sqrt(diag(vcovHC(m5)))


m6 <- d[bounce == 0 & Gender != 'U', lm(completion ~ factor(Year_Graduation) * Block + Gender)]
rse6 <- sqrt(diag(vcovHC(m6)))

stargazer(m5, m6,
          type="text",
          se = list(rse5, rse6),
          
          no.space = T,
          omit.stat = c('ser', 'f', 'adj.rsq'),
          omit = c('Gender'),
          add.lines = list(c('Gender Fixed Effects?', 'No', 'Yes'),
                           c('Excl. Gender Unknown?', 'Yes', 'Yes')),

          title = "Heterogeneous Treatment Effect",
          covariate.labels = c("Graduation: 2016", "Graduation: 2017",
                               "Graduation: 2018", "Graduation: 2019",
                               "Graduation: 2020", "Graduation: 2021",
                               "Group: Direct", "Group: Philanthropic",
                               "2016 + Direct", "2017 + Direct",
                               "2018 + Direct", "2019 + Direct",
                               "2020 + Direct", "2021 + Direct",
                               "2016 + Philanthropic", "2017 + Philanthropic",
                               "2018 + Philanthropic", "2019 + Philanthropic",
                               "2020 + Philanthropic", "2021 + Philanthropic",
                               "Constant"),
          dep.var.labels = "Survey Completion")
```


